/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import advancedFields from "@webbycrown/advanced-fields/strapi-admin";
import autoSlugManager from "strapi-plugin-auto-slug-manager-a-mi13/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "strapi-cloud": strapiCloud,
    "color-picker": colorPicker,
    "users-permissions": usersPermissions,
    "advanced-fields": advancedFields,
    "auto-slug-manager": autoSlugManager,
  },
});
